/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as PartiesPartyIDImport } from './routes/parties.$partyID'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const PartiesPartyIDRoute = PartiesPartyIDImport.update({
  id: '/parties/$partyID',
  path: '/parties/$partyID',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/parties/$partyID': {
      id: '/parties/$partyID'
      path: '/parties/$partyID'
      fullPath: '/parties/$partyID'
      preLoaderRoute: typeof PartiesPartyIDImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/about': typeof AboutRoute
  '/parties/$partyID': typeof PartiesPartyIDRoute
}

export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/parties/$partyID': typeof PartiesPartyIDRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/about': typeof AboutRoute
  '/parties/$partyID': typeof PartiesPartyIDRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/about' | '/parties/$partyID'
  fileRoutesByTo: FileRoutesByTo
  to: '/about' | '/parties/$partyID'
  id: '__root__' | '/about' | '/parties/$partyID'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AboutRoute: typeof AboutRoute
  PartiesPartyIDRoute: typeof PartiesPartyIDRoute
}

const rootRouteChildren: RootRouteChildren = {
  AboutRoute: AboutRoute,
  PartiesPartyIDRoute: PartiesPartyIDRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/about",
        "/parties/$partyID"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/parties/$partyID": {
      "filePath": "parties.$partyID.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
